# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CharaTime-sys"

[social.params]
icon = "brand-github"

[[social]]
identifier = "fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/yuan-qingpeng-585233334/"

[social.params]
icon = "brand-twitter"
